### ISSUE TITLE
Create Libgee Developer Guide

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/vala-docs#11]
Original Content: https://wiki.gnome.org/Projects/Libgee

Update original content so that:
- It mentions the source code now being inside the Vala compiler repo
- Link source code link to directory in Vala compiler repo
- Remove Contact info

**Comment by lw64** [comment]
> It mentions the source code now being inside the Vala compiler repo

that is not true, valac has only a copy of it in-tree.

Since the wiki will be soon read-only, and the last news is from 2018 anyways, I don't think anyone will consider this as up to date, and look for other sources instead.
